spring:
  application:
    name: diptish-website-crawler


diptish:
  local-file-path: D:\JAVA Workspace\diptish-website-crawler\diptish-website-crawler\     #Location where you want the file to be created
  local-file-name: doctor-profile-link                                                    #Can be anything
  wait-time: 1000                                                                         #1000 = 1 second